apiVersion: v1
data:
  scalper.json: |-
    {
      "PROFILE": "TEST",
      "PAIRS": ["BTC-EUR", "ETH-EUR"],
      "TOTAL_BUDGET": 100,
      "PORTFOLIO_ALLOCATION": {
        "BTC-EUR": 60,
        "ETH-EUR": 40
      },
      "WINDOW_SIZE": 3,
      "CHECK_INTERVAL": 10,
      "RSI_INTERVAL": 60,
      "SELL_THRESHOLD": 70,
      "BUY_THRESHOLD": 30,
      "MINIMUM_PROFIT_PERCENTAGE": 1.0,
      "STOP_LOSS_PERCENTAGE": -5,
      "STOP_LOSS_MAX_RETRIES": 3,
      "STOP_LOSS_WAIT_TIME": 5,
      "TRADE_FEE_PERCENTAGE": 0.25,
      "MAX_TRADES_PER_PAIR": 1,
      "DEMO_MODE": true
    }
kind: ConfigMap
metadata:
  name: test-scalper-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-scalper
  name: test-scalper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scalper
  template:
    metadata:
      labels:
        app: test-scalper
    spec:
      containers:
      - args:
        - --config
        - /app/config/scalper.json
        image: bitvavo-scalper:0.1.23
        name: bitvavo-scalper
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/config
          name: merged-config
        - mountPath: /app/data
          name: data-volume
      initContainers:
      - command:
        - sh
        - -c
        - |
          # Kopieer alle bestanden van de scalper-config en connection-config naar de merge directory
          cp -r /scalper/* /merged/ && cp -r /connection/* /merged/
        image: busybox
        name: copy-config
        volumeMounts:
        - mountPath: /scalper
          name: test-scalper-config
        - mountPath: /connection
          name: connection-config
        - mountPath: /merged
          name: merged-config
      volumes:
      - configMap:
          name: scalper-config
        name: scalper-config
      - configMap:
          name: connection-config
        name: connection-config
      - emptyDir: {}
        name: merged-config
      - hostPath:
          path: /data
        name: data-volume
