apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://helm.influxdata.com
    targetRevision: 2.0.0 # vervang met de gewenste versie van de InfluxDB chart
    chart: influxdb2
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - "influxdb.kind.local"
        # Optioneel: stel admin credentials in (pas deze waarden aan voor productie)
        auth:
          adminUser: admin
          adminPassword: admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true