apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.8.0" # pas aan indien nodig
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
        promtail:
          enabled: true
        grafana:
          enabled: true
          installCRDs: true   # zorgt ervoor dat de Grafana CRD’s (bv. GrafanaDashboard) worden geïnstalleerd
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - "loki.kind.local"
          podSecurityPolicy:
            enabled: false   # Schakel PSP specifiek voor Grafana uit
        podSecurityPolicy:
          enabled: false     # Schakel globale PSP aanmaak uit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true