apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.8.0" # vervang dit door de gewenste chart-versie
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
        promtail:
          enabled: true
        grafana:
          enabled: true
          installCRDs: true   # zorgt ervoor dat de Grafana CRD’s (bv. voor GrafanaDashboard) worden geïnstalleerd
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - "grafana.loki.local"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true