apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.8.0" # adjust to the desired chart version
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
        promtail:
          enabled: true
        grafana:
          enabled: true
          installCRDs: true   # ensures Grafana CRDs (e.g., GrafanaDashboard) are installed
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - "loki.kind.local"
        podSecurityPolicy:
          enabled: false   # Disable PodSecurityPolicy creation to avoid API errors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true