apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.8.0" # Pas aan indien nodig
    chart: loki-stack
    helm:
      values: |
        # Globale uitschakeling van PSP
        podSecurityPolicy:
          enabled: false
          create: false

        # Loki settings
        loki:
          enabled: true
          podSecurityPolicy:
            enabled: false
            create: false

        # Promtail settings
        promtail:
          enabled: true
          podSecurityPolicy:
            enabled: false
            create: false

        # Grafana settings
        grafana:
          enabled: true
          installCRDs: true   # Zorgt ervoor dat de Grafana CRD's worden geïnstalleerd
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - "loki.kind.local"
          podSecurityPolicy:
            enabled: false
            create: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true