apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.3.0
    chart: prometheus
    helm:
      values: |
        alertmanager:
          enabled: true
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
            hosts:
              - "prometheus.kind.local"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true