apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  ingress:
    enabled: false
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_signout_menu: true
    security:
      admin_user: admin
      admin_password: admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana-dashboard